FROM ubuntu:22.04 AS builder

RUN apt-get update && apt-get install -y wget ca-certificates && rm -rf /var/lib/apt/lists/*

ARG QDRANT_VERSION=v1.16.3 # Replace with the current version
RUN wget https://github.com/qdrant/qdrant/releases/download/v1.16.3/qdrant-x86_64-unknown-linux-gnu.tar.gz
RUN tar -xvf qdrant-x86_64-unknown-linux-gnu.tar.gz
RUN ls
RUN pwd
RUN mv qdrant /usr/local/bin/qdrant

FROM ubuntu:22.04
COPY --from=builder /usr/local/bin/qdrant /usr/local/bin/qdrant

EXPOSE 6333 6334

CMD ["qdrant"]
